---
title: "Replication Exercise 4 - Instrumental Variables"
author: "Marina Merlo"
date: "30 de abril de 2019"
output: pdf_document
---

```{r, echo=FALSE, warning=F, message=F}
library(tidyverse)
library(ggplot2)
library(knitr)
library(data.table)
library(effects)
library(MASS)
library(Zelig)
library(ZeligChoice)
library(estimatr)
library(stargazer)
library(float)
library(pander)
library(texreg)
library(plm)
library(RCurl)
library(gdata) 
library(zoo)
library(gridExtra)
 
knitr::opts_chunk$set(echo = FALSE)
data <- fread("https://jonnyphillips.github.io/Methods_III/Classes/Class_6/Replication/IV.csv")
```

## 1. What is the treatment? What is the control? What is the outcome? What is the instrument for treatment?
treat is cool 
 
## 2. If we did not know about instrumental variables, the basic observational regression we might run is to examine directly how the treatment variable is related to the outcome variable. Run this basic observational regression and interpret the results. *NB:(The outcome variable is anordered categorical variable - feel free to use either an ordered multinomial logit model or a simple linearOLS regression for all the questions, it doesn’t make much difference to the results)* 

## 3. Do you trust the treatment effect estimates from Q2? What are the major threats to causal inference here? Provide concrete examples if why the estimate in Q2 might be wrong.

## 4. To conduct an Instrumental Variables analysis, we first need to make sure we have a strong‘first stage’, i.e. that our instrument (encouragement to watch the program in the phone call)predicts our treatment variable (watching the program). Using a simple regression, what is the evidence about the strength of our first stage?

## 5. Now let’s perform the 2-Stage Least Squares instrumental variables methodology. First,save the fitted values of the first stage regression from Q4 as another column in your data.

## 6. Next, run the second-stage regression of the outcome variable on those fitted values from Q5. Carefully interpret the Instrumental Variables regression result.

## 7. The only disadvantage of the 2-Stage Least Squares approach is that it doesn’t correctly estimate the standard errors for our estimated treatment effect. Conduct the equivalent all-in-one IV approach to the previous analysis using ivreg in the AER library in R or ivreg2 in Stata.

## 8. A crucial assumption for the instrumental variables regression is the exclusion restriction: that the instrument ONLY affects the outcome through the treatment, and not through anyother mechanism. We have to support this assumption by theory and supportive qualitative evidence as it cannot be empirically verified. Make the argument that the encouragement to watch the program through the phone call ONLY affects participants’ information about the proposition through its affect on watching the program.1


## 9. Now pretend you are a reviewer/critic and make the argument that the exclusion restriction assumption is likely to be false.

## 10. The authors’ analysis in Table 4 is more complicated than ours only because it includes control variables in an attempt to make sure the instrument satisfies the exclusion restriction.Add the control variables to both the first and second stage 2SLS methodology regressions and interpret the results (it will be slightly different from the values in Table 4).

## 11. To what group of people (‘population’) does our estimate of the causal effect of treatment apply? How generalizable would our results be?
